### ISSUE TITLE
Home links seems to navigate wrongly ⛵

### ISSUE THREAD

**Issue by pabloleonalcaide** [CodelyTV/job-offers#2]
Hi!
The navigation between wiki-pages doesn't work as good as expected 😟 
I think that it could be because the path was misspelled, could be?

Maybe you could use relative paths like...

```
## Posiciones abiertas

* 🌈 [Frontend Software Engineer](Frontend-Software-Engineer)
* 🧱 [Backend Software Engineer](Backend-Software-Engineer)

## Más información

* Iremos actualizando el [apartado sobre las fases del proceso de selección](👣-Fases-del-proceso-de-selección) a medida que avancemos en los procesos 🤟
* Cualquier duda que te surja puedes mandarnos un email a jobs@codely.tv y te responderemos lo antes posible 😊
```

Anyway, the job offers are amazing, good luck friends! 🤗

**Comment by JavierCane** [comment]
Fixed when we published the latest 2 job offers. Sorry for not seeing this before and thanks a lot for reporting it! 🫶🫶🫶
