### ISSUE TITLE
Minor change typo

### ISSUE THREAD

**Issue by jagarsoft** [CodelyTV/job-offers#3]
In `Nice to have` section
Where it says:
Esto no son requisitos indispensables, si no cosas que nos harán decantarnos por una persona u otra en caso de que ambas cumplan los requisitos anteriores.

Must say:
Esto no son requisitos indispensables, **sino** cosas que nos harán decantarnos por una persona u otra en caso de que ambas cumplan los requisitos anteriores.

PD: Both, frontend & backend offers

Anyway, the job offers are amazing, good luck friends! 🤗

**Comment by JavierCane** [comment]
Fixed. Thanks for the report!!
